/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.code.server.rpc.idl;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RPCError implements org.apache.thrift.TEnum {
  NO_USER(1),
  NO_MONEY(2);

  private final int value;

  private RPCError(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RPCError findByValue(int value) { 
    switch (value) {
      case 1:
        return NO_USER;
      case 2:
        return NO_MONEY;
      default:
        return null;
    }
  }
}
